version: 1
services:
  django-backend:
    image: ${DOCKER_REGISTRY}/django-backend:${VERSION}
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}

  vite-frontend:
    image: ${DOCKER_REGISTRY}/vite-frontend:${VERSION}
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - django-backend
