services:
  frontend:
    build: ./frontend
    ports:
      - "5174:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "9222:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
