version: 1
services:
  django-todo-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 21871:8000
    environment:
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}

  vite-todo-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5175:80
    depends_on:
      - django-todo-backend
