services:
  django-todo-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 21871:8000

  vite-todo-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5175:80
